import 'dart:async';
import '../models/job_card_model.dart';

class JobApi {
  static int _jobCount = 0;
  static Future<List<JobCardModel>> fetchJobs(int count) async {
    await Future.delayed(Duration(seconds: 1)); // Simulating network delay

    List<JobCardModel> jobs = [
      JobCardModel(
        title: 'Chassis Engineer',
        company: 'RedBull',
        location: 'Amsterdam, The Netherlands',
        duration: 'Feb - Aug, 2025',
        education: 'BA3/MSc',
        salary: '1000\$',
        languages: 'EN, FR',
        jobType: 'Full-Time',
        experience: 'Not needed',
        skills: ['CAD', 'FEA', 'CFD'],
        niceToHave: ['Python', 'Matlab'],
      ),
      JobCardModel(
        title: 'Automotive Engineer',
        company: 'Mercedes',
        location: 'Berlin, Germany',
        duration: 'Feb - Aug, 2025',
        education: 'BSc/MSc',
        salary: '2000\$',
        languages: 'EN, GER',
        jobType: 'Part-Time',
        experience: 'Not needed',
        skills: ['CAD', 'FEA', 'CFD'],
        niceToHave: ['No', 'Matlab'],
      ),
      JobCardModel(
        title: 'Automotive Engineer1',
        company: 'Mercedes',
        location: 'Berlin, Germany',
        duration: 'Feb - Aug, 2025',
        education: 'BSc/MSc',
        salary: '2000\$',
        languages: 'EN, GER',
        jobType: 'Part-Time',
        experience: 'Not needed',
        skills: ['CAD', 'FEA', 'CFD'],
        niceToHave: ['No', 'Matlab'],
      ),
      JobCardModel(
        title: 'Automotive Engineer2',
        company: 'Mercedes',
        location: 'Berlin, Germany',
        duration: 'Feb - Aug, 2025',
        education: 'BSc/MSc',
        salary: '2000\$',
        languages: 'EN, GER',
        jobType: 'Part-Time',
        experience: 'Not needed',
        skills: ['CAD', 'FEA', 'CFD'],
        niceToHave: ['No', 'Matlab'],
      ),
        JobCardModel(
        title: 'Mechanical Engineer',
        company: 'Ferrari',
        location: 'Milan, Italy',
        duration: 'Jan - June, 2025',
        education: 'BSc/MSc',
        salary: '2200\$',
        languages: 'EN, IT',
        jobType: 'Full-Time',
        experience: '1 year',
        skills: ['CAD', 'FEA', 'CFD'],
        niceToHave: ['Python', 'Matlab'],
      ),
      JobCardModel(
        title: 'Software Engineer',
        company: 'Tesla',
        location: 'Palo Alto, USA',
        duration: 'Mar - Sep, 2025',
        education: 'BSc/MSc',
        salary: '5000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '2 years',
        skills: ['C++', 'Python', 'Embedded Systems'],
        niceToHave: ['ROS', 'AI'],
      ),
      JobCardModel(
        title: 'Electrical Engineer',
        company: 'Porsche',
        location: 'Stuttgart, Germany',
        duration: 'May - Nov, 2025',
        education: 'MSc',
        salary: '3500\$',
        languages: 'EN, GER',
        jobType: 'Full-Time',
        experience: '3 years',
        skills: ['PCB Design', 'Embedded C', 'MATLAB'],
        niceToHave: ['Python', 'FPGA'],
      ),
      JobCardModel(
        title: 'AI Researcher',
        company: 'Google DeepMind',
        location: 'London, UK',
        duration: 'July - Dec, 2025',
        education: 'PhD',
        salary: '6000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '4 years',
        skills: ['Machine Learning', 'Deep Learning', 'Python'],
        niceToHave: ['PyTorch', 'TensorFlow'],
      ),
      JobCardModel(
        title: 'Aerodynamics Engineer',
        company: 'McLaren',
        location: 'Woking, UK',
        duration: 'Feb - Aug, 2025',
        education: 'BSc/MSc',
        salary: '2500\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '1 year',
        skills: ['CFD', 'Wind Tunnel Testing', 'CAD'],
        niceToHave: ['Python', 'Matlab'],
      ),
      JobCardModel(
        title: 'Robotics Engineer',
        company: 'Boston Dynamics',
        location: 'Boston, USA',
        duration: 'Apr - Oct, 2025',
        education: 'MSc/PhD',
        salary: '5000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '2 years',
        skills: ['ROS', 'Python', 'C++'],
        niceToHave: ['Deep Learning', 'AI'],
      ),
      JobCardModel(
        title: 'Cybersecurity Engineer',
        company: 'Palantir',
        location: 'New York, USA',
        duration: 'Mar - Sep, 2025',
        education: 'BSc/MSc',
        salary: '4500\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '2 years',
        skills: ['Penetration Testing', 'Network Security', 'C++'],
        niceToHave: ['Rust', 'Malware Analysis'],
      ),
      JobCardModel(
        title: 'Blockchain Developer',
        company: 'Ethereum Foundation',
        location: 'Remote',
        duration: 'Jan - June, 2025',
        education: 'BSc/MSc',
        salary: '4000\$',
        languages: 'EN',
        jobType: 'Remote',
        experience: '3 years',
        skills: ['Solidity', 'Ethereum', 'Smart Contracts'],
        niceToHave: ['Rust', 'Cryptography'],
      ),
      JobCardModel(
        title: 'Game Developer',
        company: 'Ubisoft',
        location: 'Montreal, Canada',
        duration: 'May - Nov, 2025',
        education: 'BSc',
        salary: '3800\$',
        languages: 'EN, FR',
        jobType: 'Full-Time',
        experience: '2 years',
        skills: ['Unity', 'C#', 'Game Design'],
        niceToHave: ['Blender', 'C++'],
      ),
      JobCardModel(
        title: 'Data Scientist',
        company: 'Netflix',
        location: 'Los Gatos, USA',
        duration: 'Aug - Dec, 2025',
        education: 'MSc/PhD',
        salary: '7000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '3 years',
        skills: ['Python', 'Pandas', 'Machine Learning'],
        niceToHave: ['Hadoop', 'TensorFlow'],
      ),
      JobCardModel(
        title: 'Cloud Engineer',
        company: 'AWS',
        location: 'Seattle, USA',
        duration: 'Feb - Aug, 2025',
        education: 'BSc/MSc',
        salary: '6000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '3 years',
        skills: ['AWS', 'Kubernetes', 'Terraform'],
        niceToHave: ['Python', 'DevOps'],
      ),
      JobCardModel(
        title: 'DevOps Engineer',
        company: 'Microsoft',
        location: 'Redmond, USA',
        duration: 'Apr - Oct, 2025',
        education: 'BSc/MSc',
        salary: '5800\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '2 years',
        skills: ['CI/CD', 'Docker', 'Kubernetes'],
        niceToHave: ['Terraform', 'AWS'],
      ),
      JobCardModel(
        title: 'NLP Researcher',
        company: 'OpenAI',
        location: 'San Francisco, USA',
        duration: 'June - Dec, 2025',
        education: 'PhD',
        salary: '9000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '4 years',
        skills: ['Python', 'NLP', 'Transformers'],
        niceToHave: ['GPT', 'Llama'],
      ),
      JobCardModel(
        title: 'Hardware Engineer',
        company: 'Intel',
        location: 'San Jose, USA',
        duration: 'Mar - Sep, 2025',
        education: 'BSc/MSc',
        salary: '4200\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '2 years',
        skills: ['VHDL', 'FPGA', 'Circuit Design'],
        niceToHave: ['Embedded C', 'Rust'],
      ),
      JobCardModel(
        title: 'Game AI Engineer',
        company: 'Rockstar Games',
        location: 'Edinburgh, UK',
        duration: 'July - Dec, 2025',
        education: 'BSc/MSc',
        salary: '5000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '3 years',
        skills: ['C++', 'AI', 'Game Engines'],
        niceToHave: ['Unreal Engine', 'Python'],
      ),
      JobCardModel(
        title: 'Bioinformatics Engineer',
        company: 'Moderna',
        location: 'Cambridge, USA',
        duration: 'Feb - Aug, 2025',
        education: 'MSc/PhD',
        salary: '7000\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '3 years',
        skills: ['Python', 'Genomics', 'Machine Learning'],
        niceToHave: ['TensorFlow', 'BioPython'],
      ),
      JobCardModel(
        title: 'Embedded Systems Engineer',
        company: 'NVIDIA',
        location: 'Santa Clara, USA',
        duration: 'Jan - July, 2025',
        education: 'BSc/MSc',
        salary: '4800\$',
        languages: 'EN',
        jobType: 'Full-Time',
        experience: '2 years',
        skills: ['C', 'RTOS', 'Embedded C'],
        niceToHave: ['FPGA', 'MATLAB'],
      ),
    ];
    List<JobCardModel> result = [];
    for (int i = 0; i < count; i++) {
      result.add(jobs[(_jobCount + i) % jobs.length]);
    }
    _jobCount = (_jobCount + count) % jobs.length;
    return result;
  }
}
