name: Flutter Android CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: 
          - { name: "appbundle", command: "flutter build appbundle --release", path: "build/app/outputs/bundle/release/app-release.aab", artifact: "android-aab" }
          - { name: "arm64-v8a", command: "flutter build apk --release --target-platform android-arm64-v8a", path: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk", artifact: "android-arm64-v8a" }
          - { name: "armeabi-v7a", command: "flutter build apk --release --target-platform android-armeabi-v7a", path: "build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk", artifact: "android-armeabi-v7a" }
          - { name: "x86_64", command: "flutter build apk --release --target-platform android-x86_64", path: "build/app/outputs/flutter-apk/app-x86_64-release.apk", artifact: "android-x86_64" }
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '23'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Setup Android signing
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/keystore.jks
        echo "storeFile=keystore.jks" >> android/key.properties
        echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
        echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
      
    - name: Build ${{ matrix.build-type.name }}
      run: ${{ matrix.build-type.command }}
      
    - name: Upload ${{ matrix.build-type.name }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.build-type.artifact }}-signed-${{ github.sha }}
        path: ${{ matrix.build-type.path }}
        retention-days: 30